version: '3'
services:
  find-a-friend:
    image: bitnami/postgresql
    ports:
      - 5432:5432
    environment:
      - POSTGRESQL_USERNAME=findafriendapi
      - POSTGRESQL_PASSWORD=123456
      - POSTGRESQL_DATABASE=findafriend